-- Run this in Supabase SQL Editor (Dashboard > SQL Editor) to create the messages table and enable Realtime.

-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id UUID NOT NULL REFERENCES public.rooms(id) ON DELETE CASCADE,
  user_name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Allow anon/authenticated to insert (per PRD: Write Access)
CREATE POLICY "Allow insert messages" ON public.messages
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- Allow anon/authenticated to read messages in rooms
CREATE POLICY "Allow read messages" ON public.messages
  FOR SELECT TO anon, authenticated
  USING (true);

-- Add messages table to Realtime publication (skip if already added)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime' AND tablename = 'messages'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
  END IF;
END $$;
